### ISSUE TITLE
Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll

### ISSUE THREAD

**Issue by yuliaria** [XAMLMarkupExtensions/WPFLocalizeExtension#362]
Hello

**Describe the bug**
I am upgrading my project from .net framework 4.7.2 to .net 6.

When I debug my project, I will get a bunch of exceptions:
`Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll`

It makes the debug much much slower now compared to when I was using .net framework 4.7.2.

**To Reproduce**
My assembly structure is something like this:
Exe > Assembly2 > Assembly3 (Exception here)

The resources are inside Assembly3.

**Expected behavior**
Is there any way to suppress the exception to make the debug faster?

**Screenshots**
<img width="431" alt="image" src="https://user-images.githubusercontent.com/6914233/186812183-e15e4fec-6db4-472e-b5f6-e7669b7df998.png">

**Enviroment (please complete the following information):**
 - OS: Windows
 - .NET: .net 6

**Additional context**
I could fix the issue by adding Assembly3 as a direct reference in my exe.
However, I would like to avoid that.

Another thing that I can do is to move all the resources to a shared assembly.
However, this will need a lot of code changes.
If this is the only way, then I will do this, but I would like to ask first, in case there is an easy way to fix this issue.

Thank you very much.

**Comment by Karnah** [comment]
Hello, @yuliaria.
Could you share the full stack trace of the exception?

**Comment by Karnah** [comment]
@yuliaria, I'm not sure why this happens after upgrading from netFramework to net6.0, but could you please check [FAQ: Startuptime for Available Cultures Search with Resx Provider](https://github.com/XAMLMarkupExtensions/WPFLocalizeExtension/blob/master/docs/FAQ.md#startuptime-for-available-cultures-search-with-resx-provider)

This exception usually happens because ResxLocalizationProviderBase doesn't know about cultures using in your application and tries all of them.

**Comment by yuliaria** [comment]
Hi @Karnah , ah, yes. Debug is much faster now. Thank you very much.
